//
// Created by jpsantos on 16-12-2023.
//

#ifndef PROJECT_AED_AIRPORTS_FLIGHTMANAGEMENT_H
#define PROJECT_AED_AIRPORTS_FLIGHTMANAGEMENT_H


class FlightManagement {

};


#endif //PROJECT_AED_AIRPORTS_FLIGHTMANAGEMENT_H
